import { useState } from "react";

function UseCase2() {
    const [count,setcount] = useState(0);
    //This code generated by me 
    // const Incremnent = () => {
    //     setcount(prevCount => prevCount + 1)
    // }
    // const Decrement= () => {
    //     setcount(prevCount => prevCount - 1)
    // }
    //code by ma'am

    const Increment = () => {
        setcount(count+1);
    }
    const Decrement = () => {
        if(count>0)
        setcount(count-1);
    else {
        alert("Count can't be negative")
    }
    }


return (<div>
        <h3>Count {count}</h3>
        <button className="btn btn-primary" onClick={Increment}>Increment</button>
        <button className="btn btn-secondary" onClick={Decrement}>Decrement</button>
    </div>  );
}

export default UseCase2;